### ISSUE TITLE
Writing Issues

### ISSUE THREAD

**Issue by AwesomeMarker100** [terranexum/OpenQGO#12]
It's important when submitting issues to keep an orderly format so that they can get solved in the most efficient way. That's why we'd appreciate using the following template linked below for submitting an issue (credit to CodeForAmerica)!: 

https://shorturl.at/kvMOX

**Comment by dahlwinters** [comment]
Thank you @AwesomeMarker100, yes, very important! Going to pin this issue so the template is visible for new issues.

**Comment by dahlwinters** [comment]
Closing this, hopefully it stays pinned. If not, will reopen.
